# Generated by Django 4.0.6 on 2022-07-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_email'),
        ('myapp', '0002_rename_book_image_book_status_alter_student_email'),
    ]

    operations = [
    ]
