# Generated by Django 4.0.5 on 2022-07-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_merge_20220720_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Status',
            field=models.CharField(default='available', max_length=1000),
        ),
    ]
