# Generated by Django 4.0.6 on 2022-08-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Status',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
