# Generated by Django 4.0.6 on 2022-08-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowers',
            name='Date_taken',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='Return_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
