# Generated by Django 4.0.6 on 2022-08-11 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_borrowers_date_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='DatePaid',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='payments',
            name='Date_Bookreturned',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='payments',
            name='fine',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
    ]
