# Generated by Django 4.0.6 on 2022-08-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_borrowers_date_taken_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowers',
            old_name='BorrowerId',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='Date_taken',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='borrowers',
            name='Return_date',
            field=models.DateTimeField(),
        ),
    ]
