# Generated by Django 4.0.6 on 2022-08-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_book_status_book_status'),
        ('myapp', '0009_rename_borrowerid_borrowers_username_and_more'),
    ]

    operations = [
    ]
